clear all

result = family_power ();
t = struct2table(result);

%%
figure
clear g
g(1,1) = gramm ( ...
    'x', t.freq_family_B, ...
    'y', t.Ef, ...
    'color', t.n_subject, ...
    'lightness', t.model_prob_winner );
g(1,1).stat_summary('type','sem','geom','line')
g(1,1).geom_abline()
g(1,1).facet_grid(categorical(t.type), [])
g(1,1).set_names(...
    'x', 'true family freq', ...
    'y', 'posterior family freq', ...
    'color', 'group size', ...
    'lightness', 'within subj effect size', ...
    'row', '' ...
        );


g(1,2) = gramm ( ...
    'x', t.freq_family_B, ...
    'y', t.xp, ...
    'color', t.n_subject, ...
    'lightness', t.model_prob_winner );
g(1,2).stat_summary('type','sem','geom','line')
g(1,2).geom_vline('xintercept',0.5)
g(1,2).geom_hline('yintercept',0.5)
g(1,2).facet_grid(categorical(t.type), [])
g(1,2).set_names(...
    'x', 'true family freq', ...
    'y', 'exceedance prob', ...
    'color', 'group size', ...
    'lightness', 'within subj effect size', ...
    'row', '' ...
        );
    
[ROC] = get_ROC (t);

g(1,3) = gramm ( ...
    'x', ROC.fpr, ...
    'y', ROC.tpr, ...
    'color', ROC.n_subject, ...
    'lightness', ROC.model_prob_winner );
g(1,3).stat_summary('type','sem','geom','line')
g(1,3).facet_grid(categorical(ROC.type), [])
g(1,3).set_names(...
    'x', 'FPR', ...
    'y', 'TPR', ...
    'color', 'group size', ...
    'lightness', 'within subj effect size', ...
    'row', '' ...
        );

g.draw


%% AUC
figure
g = gramm ( ...
    'x', categorical(ROC.n_subject), ...
    'y', ROC.auc, ...
    'lightness', ROC.model_prob_winner, ...
    'color', categorical(ROC.type));
g.stat_summary('type','sem','geom','bar'); 
g.set_names('x','group size','y','ROC-AUC','lightness','within effect size','color','method')
g.draw


%% power at 0.05 FPR

thr = find_threshold (ROC);

figure
g = gramm ( ...
    'x', categorical(thr.n_subject), ...
    'y', thr.beta, ...
    'lightness', thr.model_prob_winner, ...
    'color', categorical(thr.type));
g.stat_summary('type','sem','geom','bar'); 
g.set_names('x','group size','y','power','lightness','within effect size','color','method')
g.draw


