result = family_power ();
t = struct2table(result);

%
figure
g(1,1) = gramm ( ...
    'x', t.freq_family_A, ...
    'y', t.classic_EF(:,1), ...
    'color', t.n_subject);
g(1,1).stat_summary('type','sem','geom','line')
g(1,1).geom_abline()

g(1,2) = gramm ( ...
    'x', t.freq_family_A, ...
    'y', t.revisited_EF(:,1), ...
    'color', t.n_subject);
g(1,2).stat_summary('type','sem','geom','line')
g(1,2).geom_abline()


g(2,1) = gramm ( ...
    'x', t.freq_family_A, ...
    'y', t.classic_xp(:,1), ...
    'color', t.n_subject);
g(2,1).stat_summary('type','sem','geom','line')
g(2,1).geom_vline('xintercept',0.5)
g(2,1).geom_hline('yintercept',0.5)

g(2,2) = gramm ( ...
    'x', t.freq_family_A, ...
    'y', t.revisited_xp(:,1), ...
    'color', t.n_subject);
g(2,2).stat_summary('type','sem','geom','line')
g(2,2).geom_vline('xintercept',0.5)
g(2,2).geom_hline('yintercept',0.5)

g.draw